### ISSUE TITLE
Remove dependencies on AWT

### ISSUE THREAD

**Issue by alexruiz** [alexruiz/fest-assert-2.x#103]
So FEST-Assert can be used in Android. Eventually these assertions should be in FEST-Swing.

**Comment by Bananeweizen** [comment]
For me, it still doesn't work in Android, throwing VerifyErrors. Can someone explicitly state whether or not the library is intended to work on Android since the 2.0M8 release?

**Comment by joel-costigliola** [comment]
It is but we haven't done any real tests for that, we were thinking that removing AWT dependencies was enough.

Could you give us more information about the errors ?
We don't have an environment to test Android compatibility, is it easy to setup one ?

Thanks for reporting this problem.

**Comment by billmccord** [comment]
It appears to me that the AWT dependencies have still not been removed from fest-util. I checked the tags for both 1.2.3 (which fest-assert-core 2.0M8 depends on) and 1.2.4 (which fest-assert-core 2.0M9 depends on) and both still have a ToString class that references AWT:
https://github.com/alexruiz/fest-util/blob/fest-util-1.2.3/src/main/java/org/fest/util/ToString.java
https://github.com/alexruiz/fest-util/blob/fest-util-1.2.4/src/main/java/org/fest/util/ToString.java

I'll file an issue with fest-util to resolve this as well.

**Comment by alexruiz** [comment]
Bill, I responded to a similar thread in fest-util. Like I mentioned there, I removed that myself. The problem is how the release was done.

**Comment by joel-costigliola** [comment]
should be addressed in 2.0M10

**Comment by billmccord** [comment]
I've tested and confirmed that it is fixed. Thanks!

**Comment by joel-costigliola** [comment]
Cool ! :) 
Thanks for reporting this problem.
