### ISSUE TITLE
containsExactly does not work with SortedSet and so on

### ISSUE THREAD

**Issue by aaschmid** [alexruiz/fest-assert-2.x#104]
Unfortunately the containsExactly does not work with SortedSet and so on due to it internally generates a list and compares it with isEqualTo :(
Using Version 2.0M6
Please ask for further information but I think it should be clear so far ...

**Comment by aaschmid** [comment]
Workaround is currently assertThat(result).hasSize(2).containsSequence(a1, a2)

**Comment by joel-costigliola** [comment]
You're right, it should iterate on both actual and expected Iterable and check element one by one. 
Thanks for reporting this !

**Comment by aaschmid** [comment]
you're welcome!

**Comment by aaschmid** [comment]
Great, thanks for the fast fix ;)
