### ISSUE TITLE
package private field "info" AbstractAssert prevents extenability

### ISSUE THREAD

**Issue by aaschmid** [alexruiz/fest-assert-2.x#106]
Hi,

I would like to extend abstract class AbstractAssert<S extends AbstractAssert<S, A>, A> implements Assert<S, A>> for some specific assertions of new Objects and it's hierarchies. Is it possible to make the field "@VisibleForTesting final WritableAssertionInfo info;" protected instead of currently "package private" that it can be accessed further to create own error messages using the already available functionality of ".as(...)", ".describeAs(...)" and so on?

I do not want to break any API or something else, so this is more a question and if possible a feature request than a bug ;)

Thanks for your help!

**Comment by joel-costigliola** [comment]
Making info protected will effectively solve the problem, but this must be discussed with other fest developers.

This should not prevent you from extending Fest as explained in https://github.com/alexruiz/fest-assert-2.x/wiki/Creating-specific-assertions. It shows several way of creating its own assertions.

To see it working live, grab fest-examples (https://github.com/joel-costigliola/fest-examples/tags).

Hope that helps,

**Comment by aaschmid** [comment]
:)
Maybe you can do the discussion now and I have to deal with "info" to be package private for now ;)

Unfortunately, the extention example is a bit difficult to what I want to achieve and that's why I want to use "info" in my extention. 

Thanks for your effort.

**Comment by alexruiz** [comment]
Would a protected getter be enough?

No worries about breaking APIs. The 2.x release is not final. Till then, any changes are valid. That's the whole point of the 2.x project, to provide a better project without worrying about backwards compatibility with 1.x.

Please let us know if there is anything else that prevents you from extending FEST :)

Thanks!
-Alex

**Comment by joel-costigliola** [comment]
I'll take care of this one, it will allow me to simplify the examples showing how to extend Fest assertions in fest-examples and in the wiki doc.

**Comment by aaschmid** [comment]
Hi, a protected getter will be enough.
I want to use it within "Objects.instance().assertEqual(info, actual, expected)" where I want to use actual as well ;)
I do not see the point why the field cannot be protected as actual, though ... 
However it is your decision and if it is better in your mind ...

All-in-all I will be lucky that I can just re-use "info". So far, thanks a lot ...

Cheers,
  Andreas

**Comment by joel-costigliola** [comment]
Simple curiosity :)  what do you try to achieve ?

**Comment by aaschmid** [comment]
I wrote my own EntityAssert, where "Entity" is some entity defined and returned by a foreign API. This *Assert is returned using my own assertThat (similar to the examples in https://github.com/alexruiz/fest-assert-2.x/wiki/Creating-specific-assertions). Furthermore within in my special assertions like "assertThat(response).correspondsTo(request)" I would like to do some checks, e.g. "Objects.equals(info, actual.getId(), request.getId())" and so on. To have not to override methods like "as", "describeAs" I want to have access to the "WritableAssertionInfo" (therefore a protected getter will be adequate ... and as the WritableAssertionInfo is very simple and have getter and setter it should also met every possible requirement ;) ).

Thanks for your effort and the fast solution.

One last question: Which version will contain the fix and when will it be accessible?

Cheers
