### ISSUE TITLE
POM for 2.0M7 Downloads Only fest-util

### ISSUE THREAD

**Issue by crgardner** [alexruiz/fest-assert-2.x#107]
This snippet in my pom

<dependency>
   <groupId>org.easytesting</groupId>
   <artifactId>fest-assert-core</artifactId>
   <version>2.0M7</version>
</dependency>

provides only fest-util-1.2.2.jar.

Shouldn't fest-assert-core-2.0M7.jar be available?

**Comment by joel-costigliola** [comment]
it is, check this URL : http://search.maven.org/#artifactdetails|org.easytesting|fest-assert-core|2.0M7|jar

regards

**Comment by crgardner** [comment]
Sorry not sure what I'm supposed to here.

**Comment by joel-costigliola** [comment]
It's difficult to help without details, I suggest you to follow the steps described in our doc : https://github.com/alexruiz/fest-assert-2.x/wiki/One-minute-starting-guide

**Comment by crgardner** [comment]
I followed the directions, but only the util jar comes down via maven.
 Where is the core jar?

**Comment by joel-costigliola** [comment]
please show your pom, I can't help you with partial information.

FYI, I just made a test and it worked perfectly :

```
[INFO] Building FEST Fluent Assertions examples 1.0-SNAPSHOT
...
[INFO] Adding default classpath container: org.eclipse.jdt.launching.JRE_CONTAINER/org.eclipse.jdt.internal.debug.ui.launcher.StandardVMType/JavaSE-1.6
Downloading: http://repo.maven.apache.org/maven2/org/easytesting/fest-assert-core/2.0M7/fest-assert-core-2.0M7.pom
Downloaded: http://repo.maven.apache.org/maven2/org/easytesting/fest-assert-core/2.0M7/fest-assert-core-2.0M7.pom (3 KB at 4.7 KB/sec)
Downloading: http://repo.maven.apache.org/maven2/org/easytesting/fest-assert-core/2.0M7/fest-assert-core-2.0M7.jar
Downloaded: http://repo.maven.apache.org/maven2/org/easytesting/fest-assert-core/2.0M7/fest-assert-core-2.0M7.jar (255 KB at 779.2 KB/sec)
```

**Comment by joel-costigliola** [comment]
Feel free to add a comment if you still think there is a problem.

**Comment by crgardner** [comment]
Looks like my maven config had a problem.  Got it working yesterday.
Thanks.
