### ISSUE TITLE
Missing methods to check min and max List size

### ISSUE THREAD

**Issue by renegrob** [alexruiz/fest-assert-2.x#130]
It would be nice to be able to write something like:
assertThat(myList).size().isGreaterThan(3);

Is it feasible that size() returns a SizeAssertion while isGreater returns again the original ListAssertion?

**Comment by joel-costigliola** [comment]
You can do this, it's almost what you are asking  :

``` java
assertThat(myList.size()).isGreaterThan(3);
```

BTW, I don't think it's a good idea to switch between assertions type (in your example SizeAssertion then ListAssertion) because it's confusing when you read the code.

If it's ok for you, please close this issue.

Regards,
