### ISSUE TITLE
Bad version number in .class file

### ISSUE THREAD

**Issue by mmatloka** [alexruiz/fest-assert-2.x#134]
With fest assert 1.4 my code compiles and runs tests properly. With 2.0M8, when using assertThat in unit test I get error like: Bad version number in .class file

**Comment by joel-costigliola** [comment]
Since 2.0M8 Fest is built for java 6, what runtime version of java are you using ?
Please try to upgrade to java 6 to see if it solves the problem.

If you want to use java 5, consider using 2.0M7 version or earlier, it should work.

Hope it helps

**Comment by mmatloka** [comment]
That's the problem, we build our library for compatibility with java 5.
