### ISSUE TITLE
wiki not world-editable

### ISSUE THREAD

**Issue by gaul** [alexruiz/fest-assert-2.x#135]
I cannot edit https://github.com/alexruiz/fest-assert-2.x/wiki/Tips-and-tricks despite the disclaimer:

Please share your tips with us, this page can be edited by everybody !

**Comment by joel-costigliola** [comment]
I thought it was possible, sorry :(
I can't give you the proper rights as I'm not admin of the project but I'll ask Alex to allow people to contribute.

In the meantime, if you have a tip, can you share it with us on a comment, I'll write back to the wiki.

Thanks in advance,

Joel

**Comment by joel-costigliola** [comment]
@alexruiz : can you go in settings and give rights to everyone to update the wiki ? thanks !

**Comment by gaul** [comment]
@alexruiz Can we make the wiki world-writable?

**Comment by alexruiz** [comment]
Andrew, let me see how the wiki works. If "world-writable" means anybody
can make changes without moderation, the answer will be "No",
unfortunately. But if there is a way to do something like "pull requests"
for the wiki (or some other way to moderate-before-submit) I'm all for it.

BTW, I'm referring to the github wiki. All the stuff in CodeHaus is legacy
and we won't be updating it (probably I will just delete everything).

The move to github has been slow. Mea culpa. I work on FEST on spare time,
and frankly, with a full-time job and a family it is pretty hard to find
spare time. We will get there...thanks for the patience! :)

Cheers!

**Comment by joel-costigliola** [comment]
IMO, I think we can let Fest users edit freely this wiki.
All changes are in git so we can easily rollback an update, moreover we know who did the update so it's not anonymous.

Let's trust our users here ... and if things go wrong, we only have to withdraw the edit rights and fall back to a more conservative way of maintaining this doc.

BTW the wiki git repo is : https://github.com/alexruiz/fest-assert-2.x.wiki.git

**Comment by alexruiz** [comment]
The problem is that that model will make us reactive and would require more
work to constantly scan the wiki. Pull requests is the proper way to go.
