### ISSUE TITLE
hasSize() assertion should take a long parameter instead of int

### ISSUE THREAD

**Issue by joel-costigliola** [alexruiz/fest-assert-2.x#141]
It will make the API a little bit more flexible.

**Comment by alexruiz** [comment]
Why? All size and length methods/fields in arrays, Strings and collections are ints.

**Comment by joel-costigliola** [comment]
You are right, I had some counter defined as long and had to cast them to int but my problem was really the counter not the int param.
I'm closing this 'non' issue.
