### ISSUE TITLE
Project won't compile

### ISSUE THREAD

**Issue by JanGorman** [alexruiz/fest-assert-2.x#146]
Hi there,

I checked out the source but currently the project doesn't compile (and I saw on your Jenkins page that it isn't running there either). Any plans to update the git repo to get it back running again? I love FEST, wouldn't mind getting involved in the development of it.

**Comment by dwursteisen** [comment]
Same issue here.
The problem comes from the commit https://github.com/alexruiz/fest-assert-2.x/commit/715a0f9b59a084df983f74f3e715cded3333f60d

**Comment by joel-costigliola** [comment]
Fest current build is very unstable as Alex (Fest creator) is doing a major refactoring. He has pushed his unfinished work to be able to continue working on it hence the broken build. I don't know when this refactoring will be finished.

contributors are welcome in Fest modules : [Guava](https://github.com/joel-costigliola/fest-guava-assert) and [Joda Time](https://github.com/joel-costigliola/fest-joda-time-assert) time ;-)

I'm closing this issue as it's a known temporary state

**Comment by dwursteisen** [comment]
Have you any idea of when this refactoring will ending ? 
And why Alex haven't created a refactoring branch ? So he can commit in it without breaking the main branch, and, as observer, we can see where fest-assert is going, so we can prepare/update our code base/pull request.

Regards

**Comment by joel-costigliola** [comment]
I have no news right now ... :(
I agree with the refactoring branch.

**Comment by alexruiz** [comment]
Yes, I should have created a refactoring branch. My bad. I underestimated the amont of things that are wrong in the 2.x repository.

Having said that, I don't see the point of updating to the 2.0Mn codebase. A lot of things are going to change once I'm done. It is taking longer than expected.

The breaking point was the release of FEST-Assert 2.0 M8. I should not have let it happen. There were breaking changes in FEST-Util. I should have waited to release all the FEST modules at once using the new FEST-Util.

I'm currently updating FEST-Assert 1.x, FEST-Swing and FEST-Reflect to use the same latest versions of dependencies. It is a lot of work, but I'm getting there.

**Comment by dwursteisen** [comment]
Thanks for your feedback :+1: 

Because a new branch 2.0M9 exist, may be you can setup this branch as default branch on github and building this branch on jenkins ? 

Because you have some false negative issues, like this one or https://github.com/alexruiz/fest-assert-2.x/issues/139 and https://github.com/alexruiz/fest-assert-2.x/issues/148, you may loose time for nothing. 

(This is just a suggestion)

Regards

**Comment by joel-costigliola** [comment]
Good idea, I have just switched branch in our jenkins (hosted by Cloudbees) and now build is back to successful.
