### ISSUE TITLE
ListAssert containsExactly not working

### ISSUE THREAD

**Issue by falkorichter** [alexruiz/fest-assert-2.x#156]
We´re using the ListAssert containsExactly, and I´m getting the following error

java.lang.NoSuchMethodError: org.fest.util.Collections.list([Ljava/lang/Object;)Ljava/util/List;
    at org.fest.assertions.ListAssert.containsExactly(ListAssert.java:193)

When looking at the source, I see that list() is not defined.

``` java
public ListAssert containsExactly(Object... objects) {
    validateIsNotNull(objects);
    return isNotNull().isEqualTo(list(objects));
 }
```

we´re building with maven, here are our versions:

``` xml
<fest-assert-core.version>2.0M10</fest-assert-core.version>
<fest-assert.version>1.4</fest-assert.version>
<fest-util.version>1.2.5</fest-util.version>
```

**Comment by falkorichter** [comment]
Found the problem, the util-version we are referencing fixed bug for our integration tests, but fest-assert is still referencing the old version.

Fixed by using 2 versions of util in the integration and main project

**Comment by falkorichter** [comment]
Here is the bug that forced us to move forward with the dependency https://github.com/alexruiz/fest-util/issues/16

**Comment by joel-costigliola** [comment]
You can also use [AssertJ](https://github.com/joel-costigliola/assertj-core#readme) a fork of Fest Assert that does not have any dependencyand thus no such problems.

**Comment by Hmhadhbi** [comment]
I am facing the same issue with fest-assert-1.4.jar and fest-util.version 1.2.5:
java.lang.NoSuchMethodError: org.fest.util.Collections.list([Ljava/lang/Object;)Ljava/util/List

What is the recommended version of fest-assert that fix this issue?
@joel-costigliola

**Comment by joel-costigliola** [comment]
see https://github.com/alexruiz/fest-assert-2.x/issues/170
