### ISSUE TITLE
fest-assert-1.4.jar and fest-util.version 1.2.5 NoSuchMethodError

### ISSUE THREAD

**Issue by Hmhadhbi** [alexruiz/fest-assert-2.x#170]
I am facing this issue with fest-assert-1.4.jar and fest-util.version 1.2.5:
java.lang.NoSuchMethodError: org.fest.util.Collections.list([Ljava/lang/Object;)Ljava/util/List

What is the recommended version of fest-assert that fix this issue?
@joel-costigliola

**Comment by joel-costigliola** [comment]
use assertj, it replaces Fest assert http://joel-costigliola.github.io/assertj/index.html
