### ISSUE TITLE
MapAssert should have containsKey(), containsValue() and counterparts

### ISSUE THREAD

**Issue by ash2k** [alexruiz/fest-assert-2.x#29]
This should be possible:

``` java
Map<String, Integer> map = new HashMap<String, Integer>();
assertThat(map).doesNotContainKey("test1").containsValue(2);
```

Decision to make: should this methods take generic types (`containsKey(K key)` and `containsValue(V value)`) or `Object`s? This methods in `Map` interface take `Object`s because their semantics are defined in terms of `equals()` (which takes `Object`) so the "correct" decision is to take `Object`s. But on practice this leads to coding errors when using this methods - adding a type check can at least prevent passing a wrong variable type (think about IDE's autocompletion).

My opinion - it should take generic types. If someone wants to assert with some other type it's still possible to write

``` java
Map<String, Integer> map = new HashMap<String, Integer>();
assertThat(map.doesNotContainKey(new Object())).isTrue();
```

**Comment by nfrancois** [comment]
Nice idea.
I agree with you add taking generic type.
For the moment, MapAssert does not take generic, I add it :

<code>
public class MapAssert<K, V> extends AbstractAssert<MapAssert<K, V>, Map<K,V>> implements EnumerableAssert<MapAssert<K, V>, MapEntry> {
</code>

It works fine,  I will push it soon for pull request.

For feature implementation, I can do it.

**Comment by joel-costigliola** [comment]
I will try to review it within two weeks.

Thanks guys !

**Comment by joel-costigliola** [comment]
Nicolas, I have integrated pull request #34 so you can start this one.

**Comment by nfrancois** [comment]
This issue could be close : has been pull request with #40
