### ISSUE TITLE
Move isInstanceOf and friends to AbstractAssert

### ISSUE THREAD

**Issue by ash2k** [alexruiz/fest-assert-2.x#31]
`ObjectAssert.isInstanceOf()` and `ObjectAssert.isInstanceOfAny()` can be moved to `AbstractAssert` so that all it's childs can have this assertions. Also `isNotInstanceOf()`, `isNotInstanceOfAny()` may be usefull.

**Comment by joel-costigliola** [comment]
I agree !

**Comment by nfrancois** [comment]
This issue could be close : has been pull request with #41
