### ISSUE TITLE
add class related assertions : hasSameClassAs, doesNotHaveSameClassAs, isExactlyInstanceOf, isOfAnyClassIn and counterparts

### ISSUE THREAD

**Issue by ash2k** [alexruiz/fest-assert-2.x#32]
`isOfClass(Class<?> clazz)` should check that `actual.getClass()` == `clazz`  and `isNotOfClass()` should check `!=`.
`isOfSameClass(Object other)` should check that `actual.getClass()` == `other.getClass()` and `isNotOfSameClass()` should check `!=`.

This methods should be added to `AbstractAssert` if #31 is satisfied or to `ObjectAssert` if not.

p.s. any more intuitive names?

**Comment by ash2k** [comment]
Also it may be usefull to have `Iterable` and varargs variants of `isOfAnyClass()`/`isNotOfAnyClass()`:
`isOfAnyClass(Iterable<? extends Class<?>>)`, `isOfAnyClass(Class<?>...)`,
`isNotOfAnyClass(Iterable<? extends Class<?>>)`, `isNotOfAnyClass(Class<?>...)`.

**Comment by joel-costigliola** [comment]
I would make these name changes :  
- `isOfClass`  -> `isExactlyOfClass` to mark the difference with `isInstanceOf`
- `isOfSameClass`  -> `hasSameClassAs` 

IMHO `isOfAnyClass` is not clear, I would prefer `isOfClassAmong` or `isOfClassIn` - a little bit better but not sure it's good enough ...

**Comment by nfrancois** [comment]
Why not ? <code>isExactlyInstanceOf</code>
This method already exists in <code>ThrowableAssert</code> by the same way, the errorMessage also exists.

**Comment by nfrancois** [comment]
I'm thinking about same class error message :

What did you think about : 

``` java
expected <'Yoda'> to have the same class as:<10L>(<java.lang.Long>) but was of class:<java.lang.String>
```

**Comment by joel-costigliola** [comment]
Ok if it's for `hasSameClassAs` assertion (is it ?)

**Comment by nfrancois** [comment]
Yes it is.
For hasNotSameClassAs, just add the 'not' is a strange message :

``` java
expected <'Yoda'> to have not the same class as:<'Luke">(<java.lang.Long>) but was of class:<java.lang.String>
```

Because type is repetitive.
I think something like :

``` java
expected <'Yoda'> to have not the same class as:<10L> but was of class:<java.lang.String>
```

is better

**Comment by joel-costigliola** [comment]
what about :

``` java
expected <'Yoda'> not to have not the same class as:<'Luke'> (java.lang.String)
```

We don't have to repeat actual's class since it was the same as other class.

Makes sense ?

**Comment by joel-costigliola** [comment]
fixed, thanks !
