### ISSUE TITLE
New File assertion : hasContent(String content)

### ISSUE THREAD

**Issue by joel-costigliola** [alexruiz/fest-assert-2.x#43]
We already have :

``` java
File actualFile = ... 
File fileWithExpectedContent = ...
assertThat(actualFile).hasSameContentAs(fileWithExpectedContent);
```

And we would like to have :

``` java
File actualFile = ... 
assertThat(actualFile).hasContent("some content");
```

**Comment by ash2k** [comment]
Do you mean `hasContentEqualTo()`? I think `hasContent()`/`doesNotHaveContent()` should take `byte[]` not `String` - this will make it possible to do assertions for binary files. But maybe separate assertions for binary/text files? API like this:

``` java
File actualFile = ... 
assertThat(actualFile).asTextFile("UTF-16").hasContent("some content");
assertThat(actualFile).asTextFile(Charset.forName("UTF-16")).hasContent("some content");
assertThat(actualFile).asBinaryFile().doesNotHaveContent("some other content".getBytes("UTF-8"));
```

**Comment by nfrancois** [comment]
I was thinking to this feature few days ago. I thought it need more content comparison like (not best syntax) :

``` java
assertThat(actualFile).startsWith("<xml");
assertThat(actualFile).endsWith("xml>");
assertThat(actualFile).contains("Hello");
assertThat(actualFile).matches("*Hello*");
```

Completly inspire by SringAssert :)

I think @ash2k idea about <code>asTextFile</code> and <code>asBinaryFile</code> is fine (like ObjectAssert ComparisonStrategy). 
But we should have a default comparison and i think it should be <code>asTextFile</code> because most of user want to compare content with String.

**Comment by joel-costigliola** [comment]
I agree with Nicolas  to have text as default file content and to have assertions similar to String assertions.

After reading your interesting comments, I would propose : 

``` java
File actualFile = ... 
// uses UTF-16 Charset/Encoding and considers actualFile as a text file
assertThat(actualFile).usingEncoding("UTF-16").hasContent("some content");
// uses default encoding as stated in String.getBytes() and considers actualFile as a text file
assertThat(actualFile).hasContent("some content");
```

I hesitated between usingEncoding("UTF-8") and usingCharset("UTF-8"), I have chosen because of this post :
http://www.grauw.nl/blog/entry/254

Tell me if you prefer usingCharset and why we should use it instead usingEncoding.

---

I'm ok with Mikhail proposition ...

``` java
assertThat(actualFile).asBinaryFile().hasContent("some other content".getBytes("UTF-8"));
```

... but I have another one ;-)

``` java
assertThat(actualFile).hasBinaryContent("some other content".getBytes("UTF-8"));
```

WDYT ?

**Comment by ash2k** [comment]
@joel-costigliola,

I think relying on platform encoding is a very bad idea - encoding should always be specified. If someone wants platform encoding then it can be specified explicitly with `Charset.defaultCharset()`. Often programmers tend to use the most "easy" path, not reading docs (using things like platform encoding) - that code breaks sooner or later, fails unexpectedly in production, etc. I think `String.getBytes()` should have never existed. Because of all that i think API should be designed in a way that it should be very hard and even impossible to misuse it. Maybe `hasContent(String content, Charset charset)`/`hasContent(String content, String encoding)`?

`hasBinaryContent(byte[])` is better then my proposition.

**Comment by ash2k** [comment]
Misuse scenario: developers work on Linux and implicitly use platform encoding (UTF-8 in most cases?) in tests/code. Someone wants to contribute and checkout the code on Windows/Mac OS/etc. Tests fail like for no reason. Nobody wants to contribute :-\

**Comment by joel-costigliola** [comment]
@ash2k :

I get your point on setting explicitly a charset/encoding but I also think it will make assertions less easy to use.
May be we can still use default encoding if :
- we mention the charset used when the test fails 
- be clear in javadoc that default charset is used (even though I know users don't read doc very often)

Another point comes to my mind pertaining to assertion chaining, on your example we would have to repeat the charset.
That would give :

``` java
assertThat(actualFile).hasContent("content", aCharset).startsWith("<xml", aCharset);
```

I think we could be more elegant with :

``` java
assertThat(actualFile).usingCharset(aCharset).hasContent("content").startsWith("<xml");
```

Having said that, we can enforce user to specify a charset/encoding by throwing an IllegalStateException if `hasContent(String)` is being called before `usingCharset(String)`/`usingEncoding(String)`.
That would keep API elegant and safe although a little less explicit than specifying the charset on every assertion. 

Sounds good to you ?

**Comment by ash2k** [comment]
@joel-costigliola,

the second variant also came to my mind later yesterday but with fluent API that is hard(er) to misuse:

``` java
 assertThat(actualFile).hasBinaryContent(byte[] ...).usingEncoding(String/Charset encoding).hasContent("content");
```

Showing types:

``` java
FileAssert fa = assertThat(actualFile);
fa.hasBinaryContent(byte[] ...);
TextFileAssert tfa = fa.usingEncoding(String/Charset encoding);
tfa.hasContent("content");
```

So the user just can't use `hasContent()`, which is only present in `TextFileAssert`, unless encoding is specified.

`AbstractFileAssert` extends `AbstractAssert`,
`FileAssert` extends `AbstractFileAssert`,
`AbstractTextFileAssert` extends `AbstractFileAssert`,
`TextFileAssert` extends `AbstractTextFileAssert`

**Comment by joel-costigliola** [comment]
Getting back to this issue ! 

For simplicity sake (something important in Fest), I would prefer not to force users to set a charset/encoding for text file based assertion.

After all, why asking users to set a charset if, 90% of the time, they will set the default charset - this is something we can do for them.

Now, I don't want to ignore the potential charset intricacies, I think it is just good enough to :
- we mention the charset used when the test fails 
- be crystal clear in javadoc that default charset is used if none is specified with usingEncoding

If we follow this path, then the 

``` java
// uses default charset to check text content
 assertThat(actualFile).hasContent("content");

// uses specified charset to check text content
 assertThat(actualFile).usingEncoding(String/Charset encoding).hasContent("content");
```

Last point, it is still unclear what would be best between `usingEncoding` and `usingCharset`, I still prefer `usingEncoding` but java API uses charset ...

**Comment by joel-costigliola** [comment]
`hasContent`, `hasBinaryContent` and `usingCharset` has been addressed by Olivier Michallat.
I have created another issue for the remaining assertions #79, this why I'm closing this issue.
