### ISSUE TITLE
Implement EnumAssert

### ISSUE THREAD

**Issue by Crazyjavahacking** [alexruiz/fest-assert-2.x#45]
I looks like some support for enum classes could be implemented.

The only thing that makes sense for me right now is int EnumAssert.numberOfEnumConstants().

Any other ideas?

**Comment by joel-costigliola** [comment]
As stated in your email, I'm rejecting this issue and wait for more useful stuff . 
Whenever you think of some relevant assertion on enums, just create a new issue and we will take care of it.

Regards
