### ISSUE TITLE
isLenientEqualsToByIgnoringFields() ignores null fields in expected

### ISSUE THREAD

**Issue by bowmore** [alexruiz/fest-assert-2.x#47]
The method org.fest.assertions.api.ObjectAssert#isLenientEqualsToByIgnoringFields() behaves like isLenientEqualsToByIgnoringNullFields() regarding null fields on the expected value, while it should behave like isLenientEqualsToByAcceptingFields().

As isEqualToByComparingFields() is implemented using isLenientEqualsToByIgnoringFields(), it is also affected.

I've included a failing test below that exposes the bug on both methods (paraphrasing the javadoc examples).

Tested on version 2.0M5

---

```
package bugreport;

import org.junit.Test;

import static org.fest.assertions.api.Assertions.assertThat;

public class IsLenientEqualsToByIgnoringFieldsBug {

    private static enum Race {
        HOBBIT, ELF, DWARF, HUMAN
    }

    private static class TolkienCharacter {

        private String name;
        private int age;
        private Race race;

        public TolkienCharacter(String name, int age, Race race) {
            this.name = name;
            this.age = age;
        }

        public String getName() {
            return name;
        }

        public int getAge() {
            return age;
        }

        public Race getRace() {
            return race;
        }
    }

    @Test(expected = AssertionError.class)
    public void testIsLenientEqualToByIgnoringFieldsFailsWhenExpectedFieldIsNull() {

        TolkienCharacter frodo = new TolkienCharacter("frodo", 33, Race.HOBBIT);
        TolkienCharacter mysteriousHobbit = new TolkienCharacter(null, 33, Race.HOBBIT);

        assertThat(frodo).isLenientEqualsToByIgnoringFields(mysteriousHobbit);
    }

    @Test(expected = AssertionError.class)
    public void testIsEqualToByComparingFieldsFailsWhenExpectedFieldIsNull() {

        TolkienCharacter frodo = new TolkienCharacter("frodo", 33, Race.HOBBIT);
        TolkienCharacter mysteriousHobbit = new TolkienCharacter(null, 33, Race.HOBBIT);

        assertThat(frodo).isEqualsToByComparingFields(mysteriousHobbit);
    }



}
```

**Comment by nfrancois** [comment]
The problem come from reflection with private inner class.
If you pu TolkienCharacter in public, it success.

**Comment by bowmore** [comment]
The problem occurred originally with one of our developers, using 2.0M3, in an actual test. There were no private inner classes used there. I then tried it on 2.0M5 using the test above and found the test to fail as well, so concluded it was still a problem on 2.0M5.
It is indeed reflection that makes the test fail, and the original issue on 2.0M3 has been resolved, so closing this issue.

Thanks!
