### ISSUE TITLE
isEqualTo weird behavior with generics

### ISSUE THREAD

**Issue by joel-costigliola** [alexruiz/fest-assert-2.x#57]
``` java
TolkienCharacter frodo = ... ;
// Won't compile in 2.0M6
assertThat(frodo.getClass()).isEqualTo(TolkienCharacter.class);
```

Error is :    

```
The method isEqualTo(Class<capture#1-of ? extends TolkienCharacter>) in the type 
AbstractAssert<ObjectAssert<Class<capture#1-of ? extends TolkienCharacter>>,Class<capture#1-of ? extends TolkienCharacter>> 
is not applicable for the arguments (Class<TolkienCharacter>)
```

**Comment by joel-costigliola** [comment]
I'm not sure we can do much here, this is a generic puzzle for me !

TolkienCharacter.class type is Class<TolkienCharacter>
frodo.getClass() type is Class<? extends TolkienCharacter>

We are trying to compare Class<? extends TolkienCharacter> to Class<TolkienCharacter> which are incompatible since AFAIK, Class<? extends TolkienCharacter> could be something else than Class<TolkienCharacter> (although Class<TolkienCharacter> is valid subsitute of Class<? extends TolkienCharacter).

I'm closing this ticket because Fest has class assertions :

``` java
assertThat(frodo).isInstanceOf(TolkienCharacter.class);
assertThat(frodo).isExactlyInstanceOf(TolkienCharacter.class);
```

Anyway, feel free to reopen this ticket if you are more inspired than me ...

**Comment by marcus-nl** [comment]
Although isInstanceOf and isExactlyInstanceOf are very useful for many cases, sometimes you only have a Class to test, not an instance of that class. This is the case for me in many places, so I would really like to use assertThat(Class<?>).isEqualTo(Class<?>).

It seems to me this is quite easy to solve:

``` Java
public class ClassAssert extends AbstractAssert<ClassAssert,Class<?>> {
  protected ClassAssert(Class<?> actual) {
    super(actual, ClassAssert.class);
  }
}

  // in Assertions:
  public static ClassAssert assertThat(Class<?> actual) {
    return new ClassAssert(actual);
  }
```

**Comment by joel-costigliola** [comment]
Class assertions are planned : #33 ;-)

**Comment by marcus-nl** [comment]
Great!

**Comment by alexruiz** [comment]
What prevents you from doing this:

assertThat(a.getClass()).isEqualTo(someClass)

?

Thanks,
-Alex

**Comment by marcus-nl** [comment]
Hi Alex,

As Joel wrote in the OP, that wont compile. Suppose we have these two class-variables:

``` Java
Class<?> foo = String.class;
Class<?> bar = Integer.class;
```

And then we want to compare the two:

``` Java
assertThat(foo).isEqualTo(bar);
```

The signature of this call is `assertThat(Class<?>).isEqualTo(Class<?>)`, so it looks like it should work. However, the first ? and the second ? are not regarded as the same type by the compiler (that's what the 'capture#1-of ?' and 'capture#2-of ?' in the error message means), which is required because of the way that ObjectAssert is defined.

By using ClassAssert this problem is circumvented because the parameter of assertThat and isEqualTo are both defined as `Class<?>`, instead of (in essence) `Class<T>` and `Class<T>`.

Hopefully I explained this correctly :)

**Comment by alexruiz** [comment]
Right! This will compile soon (I'm making some changes to relax generics.)

+1 for ClassAssert.

Cheers,
-Alex

**Comment by emartynov** [comment]
I'm using 2.0M8 and see this issue again. Regression?

**Comment by joel-costigliola** [comment]
Not a regression, it hasn't been fixed in 2.0M8, it should be in 2.0 (with ClassAssert). 
Alex is doing a big refactoring to make 2.0 code base cleaner so we (Fest contributors) have to wait for him to finish that refactoring before making new contribution again.

**Comment by emartynov** [comment]
Thank you for the update. 

The Milestone: 2.0M7 in the header with green lite did the confusion that it's fixed/implemented.

My warm regards to the contributors, you're doing great job. I'm looking forward for the 2.0 release :)

**Comment by joel-costigliola** [comment]
Milestone updated :)
