### ISSUE TITLE
New File assertions : canRead(), canWrite() and canExecute()

### ISSUE THREAD

**Issue by olivierdemeijer** [alexruiz/fest-assert-2.x#71]
It could be convenient to have FileAssert providing:

``` java
    assertThat(file).canRead();
    assertThat(file).canWrite();
    assertThat(file).canExecute();
```

as it provides :

``` java
    assertThat(file).isDirectory();
    assertThat(file).isFile();
```

(I can take care of the implementation)

**Comment by joel-costigliola** [comment]
Hi Olivier,

I agree, this should be convenient.
It's great if you can implement it (please read our [contributor guide](https://github.com/alexruiz/fest-assert-2.x/wiki/Contributor-guidelines) before), we will try to review and integrate your pull request in a short delay.

Thanks !

Joel

**Comment by olivierdemeijer** [comment]
Hi Joel,
Implementation is done, pull request issued. However, this is my very first
attempt to use Github, so i hope i didn't screw to much.
Obviously, if i DO screwed, just discard the changes i submitted, and let
me know where :)
A really nice library btw, thanks to all of you !
Olivier

On Fri, Jul 6, 2012 at 12:47 AM, Joel Costigliola <
reply@reply.github.com

**Comment by joel-costigliola** [comment]
canRead() and canWrite() integrated, thanks !
