### ISSUE TITLE
maven build should assure that we build a java 5 compatible version

### ISSUE THREAD

**Issue by joel-costigliola** [alexruiz/fest-assert-2.x#73]
It is not enough to have source and target set 1.5 in maven compiler plugin configuration :

```
<source>1.5</source>
<target>1.5</target>
```

It is mentioned in a note of the plugin doc suggesting : 
_To avoid this issue, you can either configure the compiler's boot classpath to match the target JRE or use the Animal Sniffer Maven Plugin to verify your code doesn't use unintended APIs._

**Comment by ansgarkonermann** [comment]
maven-animal-sniffer-plugin to the rescue.
Am 10.07.2012 22:43 schrieb "Joel Costigliola" <
reply@reply.github.com

**Comment by joel-costigliola** [comment]
Adding this should do the trick :

``` xml
<plugin>
    <groupId>org.codehaus.mojo</groupId>
    <artifactId>animal-sniffer-maven-plugin</artifactId>
    <version>1.8</version>
    <configuration>
        <signature>
            <groupId>org.codehaus.mojo.signature</groupId>
            <artifactId>java15</artifactId>
            <version>1.0</version>
        </signature>
    </configuration>
    <executions>
        <execution>
            <id>Check jre 1.5 API compatibility</id>
            <phase>test</phase>
            <goals>
                <goal>check</goal>
            </goals>
        </execution>
    </executions>
</plugin>
```

It would be better to add this in parent pom so that every fest project would be checked against java 5 API.
