### ISSUE TITLE
ObjectAssert.isLenientEquals ignores superclass fields

### ISSUE THREAD

**Issue by dpredovic** [alexruiz/fest-assert-2.x#74]
I'm not sure if this is a feature or a bug, but the ObjectAssert.isLenientEquals family of methods checks only the fields of the concrete class and ignores the fields of the superclasses (because that's what Class.getDeclaredFields() does). It should be either documented as such or fixed.

**Comment by joel-costigliola** [comment]
I would say it's a bug.
Thanks for reporting this.
