### ISSUE TITLE
Can not compare objects which implements Iterable<?>

### ISSUE THREAD

**Issue by ghost** [alexruiz/fest-assert-2.x#88]
imagine class

``` java
class A implements Iterable<A>{
     public A getPrevious(){
         // some magic
     }
}

A a1 = new A();
A a2 = new A();

// I intend to do
assertThat(a1.getPrevious()).isEqualsTo(a2);

// I can do, but this results into a ClassCastException (of course)
assertThat(a1.getPrevious()).isEqualTo((Iterator<?>) a2);
```

the assert for instances of Iterable is limited to compare the Iterators, this is limitation, an unwanted limitation I guess

**Comment by joel-costigliola** [comment]
I haven't been able to reproduce your problem, see  https://github.com/joel-costigliola/fest-examples/tree/github-88
class A is :

``` java
package org.fest.assertions.examples;

import static org.fest.assertions.api.Assertions.assertThat;

import java.util.Iterator;

class A implements Iterable<A> {
  public A getPrevious() {
    return new A();
  }

  public Iterator<A> iterator() {
    return null;
  }

  public static void main(String[] args) {
    A a1 = new A();
    A a2 = new A();
    assertThat(a1.getPrevious()).isEqualTo(a2);
  }
}
```

I'm using eclipse with a java 5  execution environment (obviously running main method leads to an AssertionError). 

Can you give a full test case with environment (jdk, os , ... ) ?

**Comment by ghost** [comment]
I did use 

import static org.fest.assertions.Assertions.assertThat;

instead of

import static org.fest.assertions.api.Assertions.assertThat;

now it runs.

thx

P.S. I did not read  the migration guide, my fault. Sry!

**Comment by joel-costigliola** [comment]
I think you have deserved a "RTFM" :o)

But no problem, enjoy fest assert 2.x and help us making it better !
