### ISSUE TITLE
Custom assertions no longer have access to their descriptions

### ISSUE THREAD

**Issue by talios** [alexruiz/fest-assert-2.x#9]
Under 1.4, a customer assertion like:

```
private AgreementAssertion hasAssociatedPolicySetCount(int expectedSize, Predicate<String> matchingString) {
  int size = 0;
  try {
    for (PartyProduct partyProduct : AgreementUtils.findAssociatedPartyProduct(agreement)) {
      if (matchingString.apply(partyProduct.getProduct().getCode())) {
        size += partyProduct.getPolicySets().size();
      }
    }
  } catch (PartyProductException e) {
     // ignore errors - no count increase
  }

  assertThat(size)
    .describedAs(description())
    .isEqualTo(expectedSize);

   return this;
 }
```

Can reuse the configured description by called description(), under the new AbstractAssertion this is no longer available. The class does contain a descriptionText() method which is package protected and annotated as @VisibeForTesting - could this be made public, or another suitable means for accessing the assertion description be added back.

**Comment by joel-costigliola** [comment]
Yes sure, I'll do it for the next release 2.0M2

**Comment by talios** [comment]
Awesome. Do you have any idea when you'd be looking to release an M2?  ( i.e. days or weeks? )

**Comment by joel-costigliola** [comment]
Days ! :)
I will release 2.0M2 this week end to make this fix available (since this is easy to solve, I don't see why you should wait for 2.0 final release while you need it)

**Comment by joel-costigliola** [comment]
Mark, I have just released 2.0M2, it should be available in couple hours (the time sonatype OSS nexus sync with maven central repo).
Tell me if it's ok for you.

**Comment by talios** [comment]
Awesome - will check it out once I get to the office ;-)  Should be online by then.

Will let you know how I get on.

**Comment by joel-costigliola** [comment]
Is the issue fixed for you so that I can close it ?

**Comment by talios** [comment]
Ewps - sorry for not updating the ticket.  Yes - this works perfectly for my needs.  Cheers.
