### ISSUE TITLE
contains etc doesn't work with iterable

### ISSUE THREAD

**Issue by astubbs** [alexruiz/fest-assert-2.x#95]
i.e i have to do

```
assertThat(myCollection).contains(myOtherCollection.toArray)
```

instead of just what i would expect:

```
assertThat(myCollection).contains(myOtherCollection)
```

**Comment by joel-costigliola** [comment]
`contains` assertion works at element level (similar to JDK collection api ), you should use `containsAll`.
You could have found that by yourself by exploring a little more the available assertions and their javadoc.

Regards,

**Comment by joel-costigliola** [comment]
feel free to reopen this issue you disagree with me.

**Comment by astubbs** [comment]
Yes, containsAll works on an iterable, but I am not after "containsAll" i am trying to check "containsAny" so to speak. I want to make sure collection A contains _no_ elements from collection B.

And I do not have permission to reopen the issue.

**Comment by astubbs** [comment]
My actual use of the code is:

```
  def a = ["red", "blue", "green"]
  def b = ["blue", "green"]
  assertThat(a).doesNotContain(b.toArray())
```

**Comment by astubbs** [comment]
With the .toArray():

```
assertThat(a).doesNotContain(b.toArray())
java.lang.AssertionError: expecting
<['red', 'blue', 'green']>
 not to contain
<['blue', 'green', 'pink']>
 but found
<['blue', 'green']>
```

without it, the assertion passes, but using the opposite:

```
assertThat(a).doesNotContain(b) // passes
assertThat(a).contains(b)
java.lang.AssertionError: expecting:
<['red', 'blue', 'green']>
 to contain:
<[['blue', 'green', 'pink']]>
 but could not find:
<[['blue', 'green', 'pink']]>
```

Very nice work btw - I'd totally forgotten how much I like Fest, and had gone back to Hamcrest :/ Got into a mess trying to do this comparison with Hamcrest and found myself here again. Home again ;)

**Comment by joel-costigliola** [comment]
Thanks for the kind words :)

What you need is something like :

``` java
assertThat(a).doesNotContainAnyElementsOf(b);
```

Please, create a new issue if you want us to add this assertion (I like the assertion naming but you may have a better name for it).

Your "opposite" assertion `assertThat(a).contains(b)`  fails because it expects b to be an element of a which is not.
Are you using groovy ? because in java, this should not compile as `contains` is a generic method :

``` java
public S contains(T... values)
```

**Comment by astubbs** [comment]
I understand why the opposite works, i just wanted to demonstrate how it compares the collections as wholes, as opposed to individual elements.

I like your name, but why not add the (Iterable i) signature to the contains, as you already have the support for an array argument?

**Comment by joel-costigliola** [comment]
That was my idea, the signature being :

``` java
public S doesNotContainAnyElementsOf(Iterable<? extends T> iterable)
```

This will be handled in #96 issue (if this signature suits you).

**Comment by astubbs** [comment]
That's great, but IMO it makes sense to also have

```
public S contains(Iterable<? extends T> iterable)
```

And yes, I am using Groovy ;)

**Comment by joel-costigliola** [comment]
I disagree because we already have `containsAll` that sticks with JDK api.

**Comment by astubbs** [comment]
But then why do you have contains(T... values)?

And containsAll does something different than contains(T... values).

**Comment by joel-costigliola** [comment]
to be able to call assert contains with one value but I admit you have a point.
I will ask for more opinions before taking a decision.

**Comment by astubbs** [comment]
I suppose, if you were going to check if a list of lists contained a list, this proposed change would break that.

But does it work as is, if you are checking if an array of arrays contains a certain array?

**Comment by joel-costigliola** [comment]
No I'm not sure it would break due to the generic signature constraint.
What I don't like here is to have the same method name to assert contains with one value or a collection of value, it does not operate at the same level which may be confusing for some people.

Actually, I don't like `containsAll` much, if I could break the API, I would chose : `containsAllElementsOf`.

**Comment by astubbs** [comment]
Why not add the new and deprecate the old?

**Comment by joel-costigliola** [comment]
yeah, another point to discuss with other fest dev :)
